# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Robb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.SmallIntegerField(choices=[(0, '报警事件'), (1, '维护事件')], default=0)),
                ('log', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Robb.Host')),
            ],
        ),
        migrations.AlterField(
            model_name='trigger',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Information'), (2, 'Warning'), (3, 'Average'), (4, 'High'), (5, 'Disaster')], verbose_name='告警级别'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Robb.Trigger'),
        ),
    ]
