# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=32, verbose_name='数据库名')),
            ],
            options={
                'verbose_name': '数据库信息',
            },
        ),
        migrations.CreateModel(
            name='DatabaseSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_size', models.CharField(max_length=32, verbose_name='数据库大小[Mb]')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('database_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.DatabaseInfo')),
            ],
            options={
                'verbose_name': '数据库大小',
            },
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
            ],
            options={
                'verbose_name': '主机信息',
            },
        ),
        migrations.CreateModel(
            name='MysqlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysql_port', models.IntegerField(verbose_name='端口')),
                ('mysql_user', models.CharField(max_length=32, verbose_name='用户')),
                ('mysql_passwd', models.CharField(max_length=32, verbose_name='密码')),
                ('mysql_socket', models.CharField(max_length=32, verbose_name='Socket')),
                ('mysql_remark', models.CharField(max_length=32, verbose_name='备注')),
                ('mysql_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.HostInfo')),
            ],
            options={
                'verbose_name': 'MySQL信息',
            },
        ),
        migrations.CreateModel(
            name='TableCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_count', models.IntegerField(verbose_name='表记录数')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '表记录数',
            },
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=32, verbose_name='数据库名')),
                ('table_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.DatabaseInfo')),
                ('table_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.HostInfo')),
                ('table_mysql', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.MysqlInfo')),
            ],
            options={
                'verbose_name': '表信息',
            },
        ),
        migrations.AddField(
            model_name='tablecount',
            name='table_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.TableInfo'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='database_mysql',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.MysqlInfo'),
        ),
    ]
